endpoints:
    - api-interface: jsonrpc
      chain-id: SUIJSONRPC
      network-address:
        address: "127.0.0.1:2220"
      node-urls: 
        - url: https://sui-mainnet-endpoint.blockvision.org
