name: master-project

volumes:
  checkpoints_data:

include:
  # - path: ./sui-sender-indexer/docker-compose.yml
  #   project_directory: ./sui-sender-indexer
  #   name: sui

  - path: ./sui_indexer_checkpointTx/docker-compose.yml
    project_directory: ./sui_indexer_checkpointTx
    name: sui
    
  # - path: ./indexer-jsonrpc-test/docker-compose.yml
  #   project_directory: ./indexer-jsonrpc-test
  #   name: sui

  # - path: ./sui/docker/sui-indexer-alt/docker-compose.yml
  #   project_directory: ./sui-indexer-alt
  #   name: sui-indexer
    
  - path: ./supabase/docker/docker-compose.yml
    project_directory: ./supabase/docker
    name: supabase
    
  - path: ./full-node/docker-compose.yml
    project_directory: ./full-node
    name: full-node

  - path: ./lava/docker/simple-provider/docker-compose.yml
    project_directory: ./lava/docker/simple-provider
    name: lava
