name: master-project

volumes:
  checkpoints_data:

include:
  - path: ./sui-sender-indexer/docker-compose.yml
    project_directory: ./sui-sender-indexer
    name: sui
    
  - path: ./supabase/docker/docker-compose.yml
    project_directory: ./supabase/docker
    name: supabase
    
  - path: ./full-node/docker-compose.yml
    project_directory: ./full-node
    name: full-node

  - path: ./lava/docker/simple-provider/docker-compose.yml
    project_directory: ./lava/docker/simple-provider
    name: lava
