# compose.override.yaml
services:
  indexer:
    volumes:
      - checkpoints_data:/checkpoints_indexer:ro
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REMOTE_STORE_URL=${REMOTE_STORE_URL}
      - START_CHECKPOINT=${START_CHECKPOINT}
      - LOCAL_MODE=${LOCAL_MODE}
      - CHECKPOINT_DIR=${CHECKPOINT_DIR}

  sui-node:
    volumes:
      - checkpoints_data:/checkpoints_indexer:rw
    ports:
      - "9081:8080"
      - "9085:8084/udp"
      - "9091:9000"
      - "9195:9184"

volumes:
  checkpoints_data: